php:
  preset: laravel
  enabled:
    - long_list_syntax
  disabled:
    - concat_without_spaces
    - not_operator_with_successor_space
    - cast_spaces
    - trailing_comma_in_multiline_array
    - heredoc_to_nowdoc
    - phpdoc_summary
    - short_list_syntax
  risky: false

vue:
  tab-width: 2
  use-tabs: false
  print-width: 120
  double-quotes: false
  trailing-commas: es5
  semicolons: true
  arrow-parens: always
  bracket-spacing: true
  indent-script-and-style: false
  whitespace-sensitivity: css
  finder:
    name: "*.vue"
    exclude:
      - "node_modules"
      - "dist"

js:
  tab-width: 2
  use-tabs: false
  print-width: 120
  double-quotes: false
  trailing-commas: es5
  semicolons: true
  arrow-parens: always
  bracket-spacing: true
  finder:
    name:
      - "*.js"
    exclude:
      - "node_modules"
      - "dist"